### ISSUE TITLE
Creare componente riutilizzabile per saltare al contenuto

### ISSUE THREAD

**Issue by giogardin** [ggardin/tecweb#118]
Aiuto alla navigazione che porta direttamente al contenuto.

- [x] definire nuova classe, visibile su `:focus`
- [x] introdurre l'id `content` nelle pagine
  - [x] 404
  - [x] about
  - [x] cerca
  - [x] collezione
  - [x] dati
  - [x] film
  - [x] index
  - [x] list
  - [x] lists
  - [x] login
  - [x] persona
  - [x] signup
  - [x] stats
  - [x] user

GitHub lo implementa così:

```html
<a href="#start-of-content" class="skip-to-content">Skip to content</a>
```

```css
.skip-to-content {
    position: absolute;
    width: 1px;
    height: 1px;
    margin: 0;
    overflow: hidden;
    clip: rect(1px, 1px, 1px, 1px);
}
.skip-to-content:focus {
    z-index: 999;
    width: auto;
    height: auto;
    clip: auto;
}
```

Nota sulle classi utilizzate per gli aiuti alla navigazione:
- `.skip-to-content` è il link a `#content`. Appare solo quando l'elemento riceve il focus, quindi quando l'utente preme tab.
- `.sr-only` (screen-reader only) è pensata per inserire testi di aiuto all'interno dei diversi contenuti. Uso classico: bottone che mostra solo un'icona.
```
<button ...>
  <span class="sr-only">Cambia tema</span>
  <img src="./icon.png" />
</button>
```
In questo modo lo SR legge "Cambia tema". Va bene per tanti altri casi.
